---
title: "Data Preparation"
author: "Sophie Hensgen"
date: "5/12/2021"
output: html_document
---

```{r packages, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tidyr)
```

## Aufbereitung


```{r Datensatz reinladen}

df_origin <- read_csv("stigma-origin-df.csv")
df_origin_nolab <- read_csv("stigma-origin-df-nolabel.csv")

```

```{r Impression}

head(df_origin)
head(df_origin_nolab)
```

```{r Aufbereitung df_origin, echo=FALSE}

# select variables, which I need for the analysis.

df_label <- df_origin %>%
  select(lfdn, c_0003, c_0004, c_0005, c_0006, v_19, v_258, v_42, v_21, v_23, v_24, v_25, v_28, v_30, v_31, v_32, v_33, v_34, v_35, v_37, v_38, v_39, v_36, v_153,v_154,v_155, v_156, v_157, v_158, v_181, v_182,v_183, v_184, v_185, v_186, v_187, v_188, v_189, v_190, v_191, v_192, v_193, v_194, v_195, v_196, v_197, v_198, v_177, v_180, v_178, v_179, v_11, v_12, v_13, v_14, v_15, v_16, v_86, v_87, v_88, v_17, v_248, v_199, v_250, v_246)

# assign column names

colnames(df_label) <- c("id","v1", "v2", "v3", "v4", "sex_p", "age_p", "land", "school", "beruf_anlernzeit", "beruf_teilfacharbeiterabschluss","beruf_abgeschlossene_lehre", "beruf_fachschulabschluss","beruf_meister_techniker", "beruf_fachhochschulabschluss","beruf_hochschulabschluss", "beruf_andere_ausbildung","beruf_andere_ausbildung_o","beruf_keine", "staatsangehörigkeit_deutsch", "staatsangehörigkeit_eu","staatsangehörigkeit_nicht_eu","geburtsort", "nachbar_v1", "heirat_v1", "arbeit_v1", "essen_v1", "freund_v1", "kinder_v1", "nachbar_v2", "heirat_v2", "arbeit_v2", "essen_v2", "freund_v2", "kinder_v2", "nachbar_v3", "heirat_v3", "arbeit_v3", "essen_v3", "freund_v3", "kinder_v3", "nachbar_v4", "heirat_v4", "arbeit_v4", "essen_v4", "freund_v4", "kinder_v4", "eigene_finanzen", "eigene_gesundheit", "andere_gesundheit", "wirtschaftliche_lage", "em_schule", "em_kontakt", "em_freizeit", "em_reisen", "em_profisport", "em_bars", "em_mp_freien", "em_mp_person", "em_keine", "einhaltung_maßnahmen", "infektion", "impfung", "impfbereitschaft", "politik")


head(df_label)

```
```{r Aufbereitung df_origin_nolab, echo=FALSE}

# select variables, which I need for the analysis.

df_nolab <- df_origin_nolab %>%
  select(lfdn, c_0003, c_0004, c_0005, c_0006, v_19, v_258, v_42, v_21, v_23, v_24, v_25, v_28, v_30, v_31, v_32, v_33, v_34, v_35, v_37, v_38, v_39, v_36, v_153,v_154,v_155, v_156, v_157, v_158, v_181, v_182,v_183, v_184, v_185, v_186, v_187, v_188, v_189, v_190, v_191, v_192, v_193, v_194, v_195, v_196, v_197, v_198, v_177, v_180, v_178, v_179, v_11, v_12, v_13, v_14, v_15, v_16, v_86, v_87, v_88, v_17, v_248, v_199, v_250, v_246)

# assign column names

colnames(df_nolab) <- c("id","v1", "v2", "v3", "v4", "sex_p", "age_p", "land", "school", "beruf_anlernzeit", "beruf_teilfacharbeiterabschluss","beruf_abgeschlossene_lehre", "beruf_fachschulabschluss","beruf_meister_techniker", "beruf_fachhochschulabschluss","beruf_hochschulabschluss", "beruf_andere_ausbildung","beruf_andere_ausbildung_o","beruf_keine", "staatsangehörigkeit_deutsch", "staatsangehörigkeit_eu","staatsangehörigkeit_nicht_eu","geburtsort", "nachbar_v1", "heirat_v1", "arbeit_v1", "essen_v1", "freund_v1", "kinder_v1", "nachbar_v2", "heirat_v2", "arbeit_v2", "essen_v2", "freund_v2", "kinder_v2", "nachbar_v3", "heirat_v3", "arbeit_v3", "essen_v3", "freund_v3", "kinder_v3", "nachbar_v4", "heirat_v4", "arbeit_v4", "essen_v4", "freund_v4", "kinder_v4", "eigene_finanzen", "eigene_gesundheit", "andere_gesundheit", "wirtschaftliche_lage", "em_schule", "em_kontakt", "em_freizeit", "em_reisen", "em_profisport", "em_bars", "em_mp_freien", "em_mp_person", "em_keine", "einhaltung_maßnahmen", "infektion", "impfung", "impfbereitschaft", "politik")


head(df_nolab)

```


###########################################################################################################################################
##                                                                                                                                       ##
##                                    Control, for distribution of vignettes                                                             ##
##                                                                                                                                       ##
###########################################################################################################################################

```{r Kontrolle v1 - v4, echo=FALSE}

# v1

count1 <- count(df_label, v1) # count how often one vignette appeared
count1 <- count1[-1,] # deleting missings
summary(count1$n) # summary

hist(count1$n) # descriptive graph

# v2

count2 <- count(df_label, v2) # count how often one vignette appeared
count2 <- count2[-1,] # deleting missings
summary(count2$n) # summary

hist(count2$n) # descriptive graph

# v3

count3 <- count(df_label, v3) # count how often one vignette appeared
count3 <- count3[-1,] # deleting missings
summary(count3$n) # summary

hist(count3$n) # descriptive graph

# v4

count4 <- count(df_label, v4) # count how often one vignette appeared
count4 <- count4[-1,] # deleting missings
summary(count4$n) # summary

hist(count4$n) # descriptive graph
```


```{r Kontrolle zusammen, echo=FALSE}

dftg <- df_label%>% 
  select(v1, v2, v3, v4)

df_long <- data.frame(v1 = unlist(dftg, use.names = FALSE))

count_long <- count(df_long, v1)
count5 <- count_long[-1,] # deleting missings
summary(count5$n) # summary

hist(count5$n) # descriptive graph
```
###########################################################################################################################################
##                                                                                                                                       ##
##                                                 Data Frame Preparation                                                                ##
##                                                                                                                                       ##
###########################################################################################################################################

```{r Creating new Variables - First Vignette}

df_prep <- df_nolab

### Gender of fictional Character

# 1 = women
# 0 = men

df_prep <- df_prep %>%
  mutate(sex_v1 = ifelse(grepl("Nina", dftg$v1), 1,
                      ifelse(grepl("Elif", dftg$v1), 1,
                             ifelse(grepl("Li-Ming", dftg$v1), 1, 0))))

### Ethnicity

# 1 = German
# 2 = Turkish
# 3 = Asian

df_prep <- df_prep %>%
  mutate(ethnicity_v1 = ifelse(grepl("M\xfcller", dftg$v1), 1,
                            ifelse(grepl("Ceylan", dftg$v1), 2, 3)))

### Ethnicity

# 22 = 22 years old
# 43 = 43 years old
# 64 = 64 years old

df_prep <- df_prep %>%
  mutate(age_v1 = ifelse(grepl("22", dftg$v1), 22,
                            ifelse(grepl("43", dftg$v1), 43, 64)))

### Occupation

# 1 = Nurse
# 2 = Cashier
# 3 = Administrative

df_prep <- df_prep %>%
  mutate(occupation_v1 = ifelse(grepl("Krankenhaus", dftg$v1), 1,
                            ifelse(grepl("Supermarkt", dftg$v1), 2, 3)))

### Occupation

# 1 = Non-Essential Worker
# 0 = Essential worker

df_prep <- df_prep %>%
  mutate(essential_v1 = ifelse(grepl("Home Office", dftg$v1), 1, 0))

### Covid-19

# 1 = Currently infected
# 2 = Former infected
# 3 = not mentioned

df_prep <- df_prep %>%
  mutate(infection_v1 = ifelse(grepl("gestern", dftg$v1), 1,
                            ifelse(grepl("drei Wochen", dftg$v1), 2, 3)))


```

```{r Creating new Variables - SecondVignette}


### Gender of fictional Character

# 1 = women
# 0 = men

df_prep <- df_prep %>%
  mutate(sex_v2 = ifelse(grepl("Nina", dftg$v2), 1,
                      ifelse(grepl("Elif", dftg$v2), 1,
                             ifelse(grepl("Li-Ming", dftg$v2), 1, 0))))

### Ethnicity

# 1 = German
# 2 = Turkish
# 3 = Asian

df_prep <- df_prep %>%
  mutate(ethnicity_v2 = ifelse(grepl("M\xfcller", dftg$v2), 1,
                            ifelse(grepl("Ceylan", dftg$v2), 2, 3)))

### Ethnicity

# 22 = 22 years old
# 43 = 43 years old
# 64 = 64 years old

df_prep <- df_prep %>%
  mutate(age_v2 = ifelse(grepl("22", dftg$v2), 22,
                            ifelse(grepl("43", dftg$v2), 43, 64)))

### Occupation

# 1 = Nurse
# 2 = Cashier
# 3 = Administrative

df_prep <- df_prep %>%
  mutate(occupation_v2 = ifelse(grepl("Krankenhaus", dftg$v2), 1,
                            ifelse(grepl("Supermarkt", dftg$v2), 2, 3)))

### Occupation

# 1 = Non-Essential Worker
# 0 = Essential worker

df_prep <- df_prep %>%
  mutate(essential_v2 = ifelse(grepl("Home Office", dftg$v2), 1, 0))

### Covid-19

# 1 = Currently infected
# 2 = Former infected
# 3 = not mentioned

df_prep <- df_prep %>%
  mutate(infection_v2 = ifelse(grepl("gestern", dftg$v2), 1,
                            ifelse(grepl("drei Wochen", dftg$v2), 2, 3)))


```


```{r Creating new Variables - Third Vignette}


### Gender of fictional Character

# 1 = women
# 0 = men

df_prep <- df_prep %>%
  mutate(sex_v3 = ifelse(grepl("Nina", dftg$v3), 1,
                      ifelse(grepl("Elif", dftg$v3), 1,
                             ifelse(grepl("Li-Ming", dftg$v3), 1, 0))))

### Ethnicity

# 1 = German
# 2 = Turkish
# 3 = Asian

df_prep <- df_prep %>%
  mutate(ethnicity_v3 = ifelse(grepl("M\xfcller", dftg$v3), 1,
                            ifelse(grepl("Ceylan", dftg$v3), 2, 3)))

### Ethnicity

# 22 = 22 years old
# 43 = 43 years old
# 64 = 64 years old

df_prep <- df_prep %>%
  mutate(age_v3 = ifelse(grepl("22", dftg$v3), 22,
                            ifelse(grepl("43", dftg$v3), 43, 64)))

### Occupation

# 1 = Nurse
# 2 = Cashier
# 3 = Administrative

df_prep <- df_prep %>%
  mutate(occupation_v3 = ifelse(grepl("Krankenhaus", dftg$v3), 1,
                            ifelse(grepl("Supermarkt", dftg$v3), 2, 3)))

### Occupation

# 1 = Non-Essential Worker
# 0 = Essential worker

df_prep <- df_prep %>%
  mutate(essential_v3 = ifelse(grepl("Home Office", dftg$v3), 1, 0))

### Covid-19

# 1 = Currently infected
# 2 = Former infected
# 3 = not mentioned

df_prep <- df_prep %>%
  mutate(infection_v3 = ifelse(grepl("gestern", dftg$v3), 1,
                            ifelse(grepl("drei Wochen", dftg$v3), 2, 3)))


```

```{r Creating new Variables - Fourth Vignette}


### Gender of fictional Character

# 1 = women
# 0 = men

df_prep <- df_prep %>%
  mutate(sex_v4 = ifelse(grepl("Nina", dftg$v4), 1,
                      ifelse(grepl("Elif", dftg$v4), 1,
                             ifelse(grepl("Li-Ming", dftg$v4), 1, 0))))

### Ethnicity

# 1 = German
# 2 = Turkish
# 3 = Asian

df_prep <- df_prep %>%
  mutate(ethnicity_v4 = ifelse(grepl("M\xfcller", dftg$v4), 1,
                            ifelse(grepl("Ceylan", dftg$v4), 2, 3)))

### Ethnicity

# 22 = 22 years old
# 43 = 43 years old
# 64 = 64 years old

df_prep <- df_prep %>%
  mutate(age_v4 = ifelse(grepl("22", dftg$v4), 22,
                            ifelse(grepl("43", dftg$v4), 43, 64)))

### Occupation

# 1 = Nurse
# 2 = Cashier
# 3 = Administrative

df_prep <- df_prep %>%
  mutate(occupation_v4 = ifelse(grepl("Krankenhaus", dftg$v4), 1,
                            ifelse(grepl("Supermarkt", dftg$v4), 2, 3)))

### Occupation

# 1 = Non-Essential Worker
# 0 = Essential worker

df_prep <- df_prep %>%
  mutate(essential_v4 = ifelse(grepl("Home Office", dftg$v4), 1, 0))

### Covid-19

# 1 = Currently infected
# 2 = Former infected
# 3 = not mentioned

df_prep <- df_prep %>%
  mutate(infection_v4 = ifelse(grepl("gestern", dftg$v4), 1,
                            ifelse(grepl("drei Wochen", dftg$v4), 2, 3)))


```

## Reshape Data

```{r Reshape Data}

df_prep_long <- df_prep %>%
  select("id","sex_v1", "sex_v2","sex_v3","sex_v4","age_v1","age_v2","age_v3","age_v4","ethnicity_v1","ethnicity_v2","ethnicity_v3","ethnicity_v4","infection_v1","infection_v2","infection_v3","infection_v4","occupation_v1","occupation_v2","occupation_v3","occupation_v4","essential_v1","essential_v2","essential_v3","essential_v4","nachbar_v1", "heirat_v1", "arbeit_v1", "essen_v1", "freund_v1", "kinder_v1", "nachbar_v2", "heirat_v2", "arbeit_v2", "essen_v2", "freund_v2", "kinder_v2", "nachbar_v3", "heirat_v3", "arbeit_v3", "essen_v3", "freund_v3", "kinder_v3", "nachbar_v4", "heirat_v4", "arbeit_v4", "essen_v4", "freund_v4", "kinder_v4", "sex_p", "age_p", "land", "school", "beruf_anlernzeit", "beruf_teilfacharbeiterabschluss","beruf_abgeschlossene_lehre", "beruf_fachschulabschluss","beruf_meister_techniker", "beruf_fachhochschulabschluss","beruf_hochschulabschluss", "beruf_andere_ausbildung","beruf_andere_ausbildung_o","beruf_keine", "staatsangehörigkeit_deutsch", "staatsangehörigkeit_eu","staatsangehörigkeit_nicht_eu","geburtsort", "eigene_finanzen", "eigene_gesundheit", "andere_gesundheit", "wirtschaftliche_lage", "em_schule", "em_kontakt", "em_freizeit", "em_reisen", "em_profisport", "em_bars", "em_mp_freien", "em_mp_person", "em_keine", "einhaltung_maßnahmen", "infektion", "impfung", "impfbereitschaft", "politik") %>%
  gather(key, value, sex_v1:kinder_v4) %>%
  separate(key, c("type", "vignr")) %>%
  spread(type, value)

df_origin
```

## Creating New Variables

```{r creating new Variables land}

### bundesland - Bund

# 1 = BaWü
# 2 = Bayern
# 3 = Berlin
# 4 = Brandenburg (ost)
# 5 = Bremen
# 6 = Hamburg
# 7 = Hessen
# 8 = MeckPom (ost)
# 9 = Niedersachsen
# 10 = NRW
# 11 = Rheinland-Pfalz
# 12 = Saarland
# 13 = Sachsen (ost)
# 14 = Sachsen-Anhalt (ost)
# 15 = Schleswig-Holstein
# 16 = Thüringen (ost)


### bundesland - Ost/West

# 1 = West
# 0 = East

df_prep_long <- df_prep_long %>%
  mutate(bund = ifelse(land == c(4, 8, 13, 14, 16), 0, 1))
         
### Berufsausbildung

# 1 = Beruflich-betriebliche Anlernzeit mit Abschlusszeugnis, aber keine Lehre 
# 2 = Teilfacharbeiterabschluss 
# 3 = Abgeschlossene Lehre 
# 4 = (Berufs-) Fachschulabschluss 
# 5 = Meister-, Techniker- oder gleichwertiger Fachschulabschluss 
# 6 = Fachhochschulabschluss (auch Abschluss einer Ingenieurschule) 
# 7 = Hochschulabschluss
# 8 = Andere Abschluss
# 9 = kein Abschluss
# 99 = Missing

df_prep_long <- df_prep_long %>%
  mutate(beruf = ifelse(beruf_anlernzeit == 1, 1,
                            ifelse(beruf_teilfacharbeiterabschluss == 1, 2, 
                                   ifelse(beruf_abgeschlossene_lehre == 1, 3, 
                                          ifelse(beruf_fachschulabschluss == 1, 4,
                                                 ifelse(beruf_meister_techniker == 1, 5, 
                                                        ifelse(beruf_meister_techniker == 1, 6, 
                                                               ifelse(beruf_hochschulabschluss == 1, 7, 
                                                                      ifelse(beruf_andere_ausbildung == 1, 8, 
                                                                             ifelse(beruf_keine == 1, 9, 99))))))))))


### Staatsangehörigkeit

# 1 = Deutsche
# 2 = EU-Land
# 3 = Non-EU-Land
# 4 = Deutsch + EU-Land
# 5 = Deutsch + Non-EU-Land
# 6 = EU-Land + Non-EU-Land
# 99 = Missing

df_prep_long <- df_prep_long %>%
  mutate(staat = ifelse(staatsangehörigkeit_deutsch == 1, 1,
                        ifelse(staatsangehörigkeit_eu == 1, 2,
                               ifelse(staatsangehörigkeit_nicht_eu == 1, 3,
                                      ifelse(staatsangehörigkeit_deutsch == 1 & staatsangehörigkeit_eu == 1, 4,
                                             ifelse(staatsangehörigkeit_deutsch == 1 & staatsangehörigkeit_nicht_eu == 1, 5,
                                                    ifelse(staatsangehörigkeit_eu == 1 & staatsangehörigkeit_nicht_eu == 1, 6, 99)))))))

### Impfung

#neue Variable:

# 1 = Impfbereit (inklusiv bereits geimpfte und zukünftig)
# 2 = nicht Impfbereit 

df_prep_long$impfbereitschaft
df_prep_long$impfung

df_prep_long <- df_prep_long %>%
  mutate(ein_impfung = ifelse(impfung == 1, 1,
                              ifelse(impfung == 2, 1,
                                     ifelse(impfung == 3 & impfbereitschaft == 1, 1,
                                            ifelse(impfung == 3 & impfbereitschaft == 2, 1,
                                                   ifelse(impfung == 3 & impfbereitschaft == 3, 2,
                                                          ifelse(impfung == 3 & impfbereitschaft == 4, 2, 99)))))))
                             

### Politik

# neue Variable: Rechts - Mitte - Links

# 1 = Links
# 2 = Mitte
# 3 = Rechts

df_prep_long <- df_prep_long %>%
  mutate(pol_short = ifelse(politik == 0, 99,
                            ifelse(politik <= 4, 1,
                                   ifelse(politik >= 5 & politik <= 7, 2,
                                          ifelse(politik >= 8, 3, 99)))))


### School 

# new Variable: 

# 1 = lower secondary
# 2 = higher secondary
# 3 = no 
# 99 = Missings (Other) Maybe look into them and address them accordingly

df_prep_long <-  df_prep_long %>%
  mutate(education_short = ifelse(school >= 3 & school <= 4, 1,
                                  ifelse(school >= 5 & school <= 6, 2,
                                         ifelse(school == 2, 3, 99))))

count(df_prep_long, school)
count(df_prep_long, education_short)
```

## Saving Data Frame

```{r Saving DataFrame}

write_csv(df_prep_long, "df-preparation.csv")

```











































